set(__QT_DEPLOY_TARGET_core_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/core/libcore.a)
set(__QT_DEPLOY_TARGET_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_crypto_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/crypto/libcrypto.a)
set(__QT_DEPLOY_TARGET_crypto_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_formats_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/formats/libformats.a)
set(__QT_DEPLOY_TARGET_formats_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_sync_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/sync/libsync.a)
set(__QT_DEPLOY_TARGET_sync_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_tts_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/tts/libtts.a)
set(__QT_DEPLOY_TARGET_tts_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_ereader_FILE /home/jessie/Documents/my ereader/build-android-arm64/src/app/libereader_arm64-v8a.so)
set(__QT_DEPLOY_TARGET_ereader_TYPE MODULE_LIBRARY)
