if (USE_BUNDLED_LIBARCHIVE)
  set(LIBARCHIVE_BUNDLED_ROOT "${CMAKE_SOURCE_DIR}/third_party/install/libarchive")
endif()

set(LIBARCHIVE_AVAILABLE FALSE)

if (USE_BUNDLED_LIBARCHIVE)
  set(_libarchive_inc "${LIBARCHIVE_BUNDLED_ROOT}/include")
  set(_libarchive_lib "${LIBARCHIVE_BUNDLED_ROOT}/lib/libarchive.so")
  if (EXISTS "${_libarchive_inc}" AND EXISTS "${_libarchive_lib}")
    add_library(Archive::Archive INTERFACE IMPORTED)
    target_include_directories(Archive::Archive INTERFACE "${_libarchive_inc}")
    target_link_libraries(Archive::Archive INTERFACE "${_libarchive_lib}")
    set(LIBARCHIVE_AVAILABLE TRUE)
    add_compile_definitions(HAVE_LIBARCHIVE=1)
  endif()
endif()

if (NOT LIBARCHIVE_AVAILABLE)
  find_package(LibArchive QUIET)
  if (LibArchive_FOUND)
    set(LIBARCHIVE_AVAILABLE TRUE)
    add_compile_definitions(HAVE_LIBARCHIVE=1)
  endif()
endif()
