if (USE_BUNDLED_POPPLER)
  set(POPPLER_BUNDLED_ROOT "${CMAKE_SOURCE_DIR}/third_party/install/poppler")
  if (EXISTS "${POPPLER_BUNDLED_ROOT}")
    list(PREPEND CMAKE_PREFIX_PATH "${POPPLER_BUNDLED_ROOT}")
  endif()
endif()

find_package(PopplerQt6 QUIET)
if (PopplerQt6_FOUND)
  add_compile_definitions(HAVE_POPPLER_QT6=1)
else()
  find_package(PkgConfig QUIET)
  if (PkgConfig_FOUND)
    if (USE_BUNDLED_POPPLER)
      set(ENV{PKG_CONFIG_PATH} "${POPPLER_BUNDLED_ROOT}/lib/pkgconfig")
    endif()
    pkg_check_modules(POPPLER_QT6 QUIET IMPORTED_TARGET poppler-qt6)
    if (POPPLER_QT6_FOUND)
      add_library(Poppler::Qt6 INTERFACE IMPORTED)
      target_link_libraries(Poppler::Qt6 INTERFACE PkgConfig::POPPLER_QT6)
      add_compile_definitions(HAVE_POPPLER_QT6=1)
    endif()
  endif()
endif()
