if (USE_BUNDLED_POPPLER)
  set(POPPLER_BUNDLED_ROOT "${CMAKE_SOURCE_DIR}/third_party/install/poppler")
endif()

set(POPPLER_QT6_AVAILABLE FALSE)

if (USE_BUNDLED_POPPLER)
  set(_poppler_qt6_inc "${POPPLER_BUNDLED_ROOT}/include/poppler/qt6")
  set(_poppler_qt6_lib "${POPPLER_BUNDLED_ROOT}/lib/libpoppler-qt6.so")
  set(_poppler_core_lib "${POPPLER_BUNDLED_ROOT}/lib/libpoppler.so")
  if (EXISTS "${_poppler_qt6_inc}" AND EXISTS "${_poppler_qt6_lib}" AND EXISTS "${_poppler_core_lib}")
    add_library(Poppler::Qt6 INTERFACE IMPORTED)
    target_include_directories(Poppler::Qt6 INTERFACE "${_poppler_qt6_inc}")
    target_link_libraries(Poppler::Qt6 INTERFACE "${_poppler_qt6_lib}" "${_poppler_core_lib}")
    set(POPPLER_QT6_AVAILABLE TRUE)
    add_compile_definitions(HAVE_POPPLER_QT6=1)
  endif()
endif()

if (NOT POPPLER_QT6_AVAILABLE)
  find_package(PopplerQt6 QUIET)
  if (PopplerQt6_FOUND)
    set(POPPLER_QT6_AVAILABLE TRUE)
    add_compile_definitions(HAVE_POPPLER_QT6=1)
  endif()
endif()
